version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notessecret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+aiomysql://notesuser:notessecret@db:3306/notesdb
      - JWT_SECRET=supersecretjwtkeychange
      - CORS_ORIGINS=http://localhost:3000
      - COOKIE_DOMAIN=localhost
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"

volumes:
  db_data:
